# ==========================================================================
# Project:   OeffiNpc
# Copyright: @2011 My Company, Inc.
# ==========================================================================

# Add initial buildfile information here
config :all,
:required => [:sproutcore, "sproutcore/statechart", "raphaeljs"]

proxy '/static', :to => 'oeffinpc.appspot.com'
proxy '/', :to => 'localhost:3000'

